name: 'Terraform Format and Validate'

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest
    name: Terraform Format
    steps:
    - name: Checkout
      uses: actions/checkout@v4
   
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.12.2

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: false
